AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Cloudformation custom resource to manage service catalog products

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  UpdateProvisioningArtifactFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: product_provider/app.lambda_handler
      Runtime: python3.7
      Role: !GetAtt UpdateProvisioningArtifactFunctionRole.Arn

  UpdateProvisioningArtifactFunctionRole:   # execute lambda function with this role
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSServiceCatalogAdminFullAccess

Outputs:
  UpdateProvisioningArtifactFunctionArn:
    Description: "Deprecate product versions function ARN"
    Value: !GetAtt UpdateProvisioningArtifactFunction.Arn
    Export:
      Name:
        Fn::Sub: ${AWS::Region}-${AWS::StackName}-UpdateProvisioningArtifactFunctionArn
  UpdateProvisioningArtifactFunctionRoleArn:
    Description: "Implicit IAM Role created for deprecate product version function"
    Value: !GetAtt UpdateProvisioningArtifactFunctionRole.Arn
    Export:
      Name:
        Fn::Sub: ${AWS::Region}-${AWS::StackName}-UpdateProvisioningArtifactFunctionRoleArn
